name: CustomEffects
version: '0.1'
main: me.deadybbb.customeffects.CustomEffects
api-version: '1.20'
authors: [ Ybbb ]
dependencies:
  server:
    MCKotlin-Paper:
      load: BEFORE
      required: true
    YbbbBasicModule:
      load: BEFORE
      required: true
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true